name: DiscordSocialSpy
version: 1.3
main: net.siberanka.discordsocialspy.DiscordSocialSpyPlugin
api-version: 1.16
folia-supported: true
commands:
  discordsocialspy:
    description: Main command for DiscordSocialSpy
    usage: /discordsocialspy <reload|cmd>
    aliases:
      - dss
permissions:
  discordsocialspy.use:
    default: op
  discordsocialspy.reload:
    default: op
  discordsocialspy.cmd:
    default: op
